---
- name: Load configuration
  include_vars:
    file: config.yml

- name: Load modules and capture environment
  shell: |
    source /etc/profile.d/modules.sh
    {% for module in hpc_modules %}
    module load {{ module }}
    {% endfor %}
    which python3
    printenv
  register: module_env
  changed_when: false

- name: Set Python interpreter path
  set_fact:
    python_path: "{{ module_env.stdout_lines[0] }}"

- name: Clone Vectoria Git repository
  git:
    repo: https://gitlab.hpc.cineca.it/eurocc/vectoria.git
    dest: "{{ install_path }}/vectoria"
    version: eurocc_release
  environment:
    PATH: "{{ module_env.stdout_lines | select('match', '^PATH=') | first | regex_replace('^PATH=','') }}"

- name: Create virtual environment
  command: "{{ python_path }} -m venv --system-site-packages {{ install_path }}/vectoria_env"
  args:
    creates: "{{ install_path }}/vectoria_env"
  environment:
    PATH: "{{ module_env.stdout_lines | select('match', '^PATH=') | first | regex_replace('^PATH=','') }}"

- name: Install package in virtual environment
  pip:
    name: "{{ install_path }}/vectoria"
    virtualenv: "{{ install_path }}/vectoria_env"
    virtualenv_site_packages: true
    editable: true
  environment:
    PATH: "{{ module_env.stdout_lines | select('match', '^PATH=') | first | regex_replace('^PATH=','') }}"