---
- name: Load configuration
  include_vars:
    file: config.yml

- name: Clone Vectoria Git repository
  git:
    repo: https://gitlab.hpc.cineca.it/eurocc/vectoria.git
    dest: "{{ install_path }}/vectoria"
    version: eurocc_release  # 

- name: Install Vectoria on HPC
  shell: |
    {% for module in hpc_modules %}
    module load {{ module }}
    {% endfor %}
    python -m venv {{ install_path }}/vectoria_env --system-site-packages
    source {{ install_path }}/vectoria_env/bin/activate
    pip install -e {{ install_path }}/vectoria