---
- name: Load configuration
  include_vars:
    file: config.yml

- name: Create remote directory
  file:
    path: "{{ install_path }}"
    state: directory

- name: Clone Vectoria Git repository
  git:
    repo: https://github.com/Eurocc-Italy/Vectoria.git
    dest: "{{ install_path }}/vectoria"
  ignore_errors: true

- name: Install Vectoria on HPC
  shell: |
    {% if hpc_modules %}
    {% for module in hpc_modules %}
    module load {{ module }}
    {% endfor %}
    {% endif %}
    python -m venv {{ install_path }}/vectoria_env --system-site-packages
    source {{ install_path }}/vectoria_env/bin/activate
    pip install -e {{ install_path }}/vectoria

- name: Write default_config.yaml
  template:
    src: default_config.j2
    dest: "{{ install_path }}/vectoria/etc/default/default_config.yaml"

- name: Write setup_vectoria.sh
  template:
    src: setup_vectoria.j2
    dest: "{{ install_path }}/vectoria/bin/setup_vectoria.sh"

- name: Write start_build_index.sbatch
  template:
    src: start_build_index.j2
    dest: "{{ install_path }}/vectoria/bin/start_build_index.sbatch"

- name: Write start_inference.sbatch
  template:
    src: start_inference.j2
    dest: "{{ install_path }}/vectoria/bin/start_inference.sbatch"

- name: Create results directory
  file:
    path: "{{ install_path }}/vectoria/test/results"
    state: directory

- name: Create documents directory
  file:
    path: "{{ install_path }}/docs"
    state: directory