---
- name: Load configuration
  include_vars:
    file: config.yml

- name: Load git-lfs module and capture environment
  shell: |
    source /etc/profile.d/modules.sh
    module load git-lfs
    printenv
  register: module_env
  changed_when: false

- name: Install embedder model (BGE-M3)
  git:
    repo: "git@hf.co:{{ embedder_model }}"
    dest: "{{ install_path }}/embedder_model"
  environment:
    PATH: "{{ module_env.stdout_lines | select('match', '^PATH=') | first | regex_replace('^PATH=','') }}"

- name: Install reranker model (BGE-reranker-V2-gemma)
  git:
    repo: "git clone git@hf.co:{{ reranker_model }}"
    dest: "{{ install_path }}/reranker_model"
  environment:
    PATH: "{{ module_env.stdout_lines | select('match', '^PATH=') | first | regex_replace('^PATH=','') }}"

- name: Install inference engine (LLAMA-3.1-8B)
  git:
    repo: "git@hf.co:{{ inference_engine }}"
    dest: "{{ install_path }}/inference_engine"
  environment:
    PATH: "{{ module_env.stdout_lines | select('match', '^PATH=') | first | regex_replace('^PATH=','') }}"