---
- name: Include module configuration
  include_vars:
    file: modules.yml

- name: Load modules and capture environment
  shell: |
    source /etc/profile.d/modules.sh
    {% for module in modules_to_load %}
    module load {{ module }}
    {% endfor %}
    which python3
    printenv
  register: module_env
  changed_when: false

- name: Set Python interpreter path
  set_fact:
    python_path: "{{ module_env.stdout_lines[0] }}"

- name: Clone Vectoria Git repository
  git:
    repo: https://gitlab.hpc.cineca.it/eurocc/vectoria.git
    dest: vectoria
    version: eurocc_release
  environment:
    PATH: "{{ module_env.stdout_lines | select('match', '^PATH=') | first | regex_replace('^PATH=','') }}"

- name: Create virtual environment
  command: "{{ python_path }} -m venv --system-site-packages ~/vectoria-env"
  args:
    creates: "~/vectoria-env"
  environment:
    PATH: "{{ module_env.stdout_lines | select('match', '^PATH=') | first | regex_replace('^PATH=','') }}"

- name: Install package in virtual environment
  pip:
    name: ~/vectoria
    virtualenv: ~/vectoria-env
    virtualenv_site_packages: true
  environment:
    PATH: "{{ module_env.stdout_lines | select('match', '^PATH=') | first | regex_replace('^PATH=','') }}"