---
# Path where Vectoria and related files will be stored
install_path: /path/to/install/dir

# Modules to load for git-lfs on HPC
git_lfs_modules:
  - git-lfs

# Modules to load for Vectoria on HPC
hpc_modules:
  - profile/ai-module
  - ai/2.2.0

# LLM models to be used
embedder_model: BAAI/bge-m3
reranker_model: BAAI/bge-reranker-v2-gemma
inference_engine: meta-llama/Llama-3.1-8B-Instruct

# Scratch directory to be used on HPC
tmpdir: /path/to/scratch/dir

# HPC settings
account: hpc_account  # user with HPC budget
partition: slurm_partition  # SLURM partition for jobs
cpus: 32
gpus: 4

# LLM settings
language: it  # it | eng
format: pdf  # pdf | docx
reranker_enabled: true  # disable for small installations
reranker_4bit: false  # 4 bit and 8 bit are mutually exclusive
reranker_8bit: false  # 4 bit and 8 bit are mutually exclusive
inference_4bit: false  # 4 bit and 8 bit are mutually exclusive
inference_8bit: true  # 4 bit and 8 bit are mutually exclusive
