# Logging
vectoria_logs_dir: ~/vectoria_logs
log_level: DEBUG
langchain_tracking: null
system_prompts_lang: eng

# Preprocessing
pp_multiprocessing: true
pp_steps: 
  - name: extract_text_from_docx_file
    filter_paragraphs: null
    dump_doc_structure_on_file: true
    regexes_for_metadata_extraction: null

  - name: remove_header
    regex: 'PROCEDURA\s+PRO\d+\s+-P-IT\s+REV\.\s+\d+\s+PRO\d\s+\d+-P-IT\s+REV\.\s+\d+\s+SELEZIONE,\s+AUTORIZZAZIONE\s+E\s+QUALIFICA\s+DEI\s+FORNITORI\s+' 
  
  - name: remove_footer
    regex: 'Template:\s+QUA\d+\s+-T-CO\s+it\s+rev\d+\s+©\s+Copyright\s+Selex\s+ES\s+S\.p\.A\.\s+\d+\s+\d+\s+–\s+Tutti\s+i\s+diritti\s+riservati\s+Pag\.\s+\d+\s+di\s+\d+'

  - name: remove_multiple_spaces
    regex: null

  - name: replace_ligatures
    regex: null
  
  - name: remove_bullets
    regex: null

  - name: recursive_character_text_splitter
    chunk_size: 1024
    chunk_overlap: 256
    separators: ["\n\n", "\n", " ", ""]
    is_separator_regex: [false, false, false, false]
    dump_chunks_on_file: true

vector_store:
  model_name: /leonardo_work/PhDLR_prod/bge-m3 # CINECA
  device: cuda
  normalize_embeddings: false

retriever:
  enabled: true
  retriever_top_k: 5
  retriever_search_type: 'mmr'
  retriever_fetch_k: 5
  retriever_lambda_mult: 0.5


reranker:
  enabled: false
  reranked_top_k: 3
  inference_engine:
    name: huggingface
    url: null
    api_key: null
    model_name: /leonardo_work/PhDLR_prod/bge-reranker-v2-gemma
    device: cuda
    load_in_4bit: true
    load_in_8bit: false
    max_new_tokens: 150
    trust_remote_code: false
    device_map: null
    temperature: 0.1

full_paragraphs_retrieval:
  enable: false

chat_history:
  enabled: false

# Inference engine
inference_engine:
  name: 'huggingface'
  url: null
  api_key: null
  # model_name: meta-llama/Meta-Llama-3.1-8B-Instruct # LEO
  # model_name: /leonardo_work/PhDLR_prod/meta-llama/Meta-Llama-3.1-8B-Instruct # WORK 8B
  # model_name: /leonardo_scratch/large/userinternal/aproia00/Meta-Llama-3-70B-Instruct # SCRATCH 70B
  # model_name: /leonardo_scratch/fast/PhDLR_prod/Meta-Llama-3.1-8B-Instruct # FAST 8B
  model_name: /dev/shm/Meta-Llama-3.1-8B-Instruct # RAM 8B
  #model_name: /dev/shm/Meta-Llama-3.1-70B-Instruct # RAM 70B
  device: cuda
  load_in_4bit: false
  load_in_8bit: true
  max_new_tokens: 150
  trust_remote_code: true
  device_map: auto
  temperature: 0.1


evaluation_tool: ragas
evaluation_engine:
  name: huggingface
  url: null
  api_key: null
  model_name: /dev/shm/Meta-Llama-3.1-8B-Instruct # RAM 8B 
  device: cuda
  load_in_8bit: true
  max_new_tokens: 150
  trust_remote_code: false