
 # Logging
vectoria_logs_dir: ~/vectoria_logs
log_level: DEBUG
langchain_tracking: null
system_prompts_lang: eng

# Preprocessing
pp_multiprocessing: true
pp_steps: 
  - name: extract_text_from_docx_file
    dump_doc_structure_on_file: true
    regexes_for_metadata_extraction: []

  - name: remove_header
    regex: null 
  
  - name: remove_footer
    regex: null

  - name: remove_multiple_spaces
    regex: null

  - name: replace_ligatures
    regex: null
  
  - name: remove_bullets
    regex: null

  - name: recursive_character_text_splitter
    chunk_size: 1024
    chunk_overlap: 256
    separators: ["\n\n", "\n", " ", ""]
    is_separator_regex: [false, false, false, false]
    dump_chunks_on_file: true

vector_store:
  name: faiss
  model_name: BAAI/bge-m3
  device: cuda
  normalize_embeddings: false

retriever:
  enabled: true
  top_k: 5
  search_type: 'mmr'
  fetch_k: 5
  lambda_mult: 0.5

reranker:
  enabled: false
  reranked_top_k: 3
  inference_engine:
    name: huggingface
    url: null
    api_key: null
    model_name: BAAI/bge-reranker-v2-gemma
    device: cuda
    load_in_4bit: true
    load_in_8bit: false
    max_new_tokens: 150
    trust_remote_code: false
    device_map: null
    temperature: 0.1

full_paragraphs_retriever:
  enabled: false

chat_history:
  enabled: false

inference_engine:
  name: huggingface
  url: null
  api_key: null
  model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
  device: cuda
  load_in_8bit: true
  max_new_tokens: 150
  trust_remote_code: true
  device_map: auto
  temperature: 0.1

evaluation:
  tool: ragas
  inference_engine:
    name: vllm
    model_name: hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4
    url: http://localhost:8899/v1
    api_key: abcd
  embeddings_engine:
    name: vllm
    model_name: BAAI/bge-multilingual-gemma2
    url: http://localhost:8898/v1
    api_key: abcd
